(() => {
const config=window.IPA_MODULE_CONFIG||{}, KEY="ipa-interaktif:listrik-dinamis:v1", N=7, state=load();
let active=Number.isInteger(state.activeStage)?state.activeStage:0, done=new Set(Array.isArray(state.completed)?state.completed:[]), mode=state.mode||config.defaultMode||"mandiri";
if(!state.sessionId) state.sessionId=id();
const tabs=[...document.querySelectorAll(".u-stage-tab")], panels=[...document.querySelectorAll(".u-stage-panel")], fill=document.getElementById("learningProgressFill"), ptxt=document.getElementById("learningProgressText"), prev=document.getElementById("uPrev"), next=document.getElementById("uNext"), complete=document.getElementById("uComplete"), toast=document.getElementById("uToast");
window.setLearningStage=show;
initMode();initIdentity();initDiag();initEngage();initReflect();initNav();restoreReflect();show(active);refreshSend();save();

function initMode(){document.querySelectorAll("[data-learning-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.learningMode==="guru"?"guru":"mandiri";applyMode();changed();save()});applyMode()}
function applyMode(){document.body.dataset.learningMode=mode;document.querySelectorAll("[data-learning-mode]").forEach(b=>b.classList.toggle("active",b.dataset.learningMode===mode));document.getElementById("modeHelp").textContent=mode==="guru"?"Pendidik mengendalikan diskusi, kapan penjelasan dibuka, dan kapan siswa berpindah tahap.":"Petunjuk, feedback, progres, dan refleksi membantu kamu belajar secara mandiri."}
function initIdentity(){const a=document.getElementById("studentName"),b=document.getElementById("studentClass");a.value=state.identity?.name||"";b.value=state.identity?.className||"";[a,b].forEach(f=>f.oninput=()=>{state.identity=state.identity||{};state.identity[f.id==="studentName"?"name":"className"]=f.value.trim();changed();save()})}
function initDiag(){document.querySelectorAll("[data-diagnostic]").forEach(g=>{const k=g.dataset.diagnostic;const paint=b=>{g.querySelectorAll("button").forEach(x=>x.classList.remove("selected","correct","wrong"));if(!b)return;b.classList.add("selected",b.dataset.correct==="true"?"correct":"wrong");const fb=g.parentElement.querySelector(".diagnostic-feedback");if(fb){fb.textContent=b.dataset.feedback||"";fb.classList.toggle("wrong",b.dataset.correct!=="true");fb.classList.toggle("correct",b.dataset.correct==="true")}};g.querySelectorAll("button").forEach(b=>b.onclick=()=>{paint(b);state.diagnostic=state.diagnostic||{};state.diagnostic[k]=b.dataset.value;save()});const v=state.diagnostic?.[k];if(v)paint(g.querySelector('[data-value="'+v+'"]'))})}
function initEngage(){document.querySelectorAll(".engage-option").forEach(b=>b.onclick=()=>{document.querySelectorAll(".engage-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.engagePrediction=b.dataset.prediction;document.getElementById("engageFeedback").textContent=mode==="guru"?"Prediksi tersimpan. Jelaskan alasanmu kepada kelompok/guru sebelum membuka Explore.":"Prediksi tersimpan. Jangan ubah dulu—uji melalui simulasi pada tahap Explore.";save()});if(state.engagePrediction)document.querySelector('[data-prediction="'+state.engagePrediction+'"]')?.classList.add("selected")}
function initReflect(){document.querySelectorAll("[data-reflection]").forEach(f=>f.oninput=()=>{state.reflections=state.reflections||{};state.reflections[f.dataset.reflection]=f.value;changed();save()});const g=document.getElementById("difficultyGrid");(config.difficultyCategories||[]).forEach(c=>{const l=document.createElement("label");l.className="difficulty-option";const i=document.createElement("input");i.type="checkbox";i.dataset.difficulty=c;i.checked=(state.difficulties||[]).includes(c);const s=document.createElement("span");s.textContent=c;l.append(i,s);g.appendChild(l)});g.onchange=()=>{state.difficulties=diffs();changed();save()};document.querySelectorAll("[data-confidence]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-confidence]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.confidence=+b.dataset.confidence;changed();save()});if(state.confidence)document.querySelector('[data-confidence="'+state.confidence+'"]')?.classList.add("selected");document.getElementById("sendFeedback").onclick=send}
function restoreReflect(){const r=state.reflections||{};document.querySelectorAll("[data-reflection]").forEach(f=>f.value=r[f.dataset.reflection]||"")}
function initNav(){tabs.forEach(t=>t.onclick=()=>show(+t.dataset.uStage));prev.onclick=()=>active>0&&show(active-1);next.onclick=()=>active<N-1&&show(active+1);complete.onclick=()=>{done.has(active)?done.delete(active):done.add(active);changed();render();save()};document.querySelectorAll("[data-go-stage]").forEach(b=>b.onclick=()=>show(+b.dataset.goStage));document.getElementById("resetLearning").onclick=()=>{if(confirm("Reset progres dan identitas lokal modul ini?")){localStorage.removeItem(KEY);location.reload()}}}
function show(i){active=Math.max(0,Math.min(N-1,i));panels.forEach((p,j)=>p.classList.toggle("active",j===active));tabs.forEach((t,j)=>{t.classList.toggle("active",j===active);t.classList.toggle("complete",done.has(j))});prev.disabled=active===0;next.disabled=active===N-1;next.style.opacity=active===N-1?".45":"1";complete.classList.toggle("done",done.has(active));complete.textContent=done.has(active)?"✓ Sudah selesai":"Tandai selesai";render();save();window.scrollTo({top:0,behavior:"smooth"})}
function render(){const c=done.size,p=Math.round(c/N*100);fill.style.width=p+"%";ptxt.textContent=c+" dari "+N+" tahap • "+p+"%";tabs.forEach((t,j)=>t.classList.toggle("complete",done.has(j)))}

async function send(){const ep=(config.feedbackEndpoint||"").trim(), snap=snapshot(), fp=JSON.stringify(snap);if(!snap.studentName||!snap.className){msg("Isi nama/nomor absen dan kelas pada tahap Orientasi.");show(0);return}if(!snap.confused&&!snap.difficulties.length&&!snap.confidence){msg("Isi minimal satu bagian refleksi.");return}if(!ep){msg("Koneksi Google Sheets belum aktif.");return}if(state.lastSentFingerprint===fp){msg("Tidak ada perubahan sejak pengiriman terakhir.");refreshSend();return}let sid=state.pendingFingerprint===fp&&state.pendingSubmissionId?state.pendingSubmissionId:id();state.pendingSubmissionId=sid;state.pendingFingerprint=fp;save();sendUI("sending");const payload={timestampClient:new Date().toISOString(),studentName:snap.studentName,className:snap.className,materialId:config.materialId,materialTitle:config.materialTitle,mode:snap.mode,understood:snap.understood,confused:snap.confused,difficulties:snap.difficulties.join(", "),confidence:confLabel(snap.confidence),completedStages:String(snap.completedStages),totalStages:String(N),submissionId:sid,sessionId:state.sessionId,templateVersion:(config.templateVersion||"")+" / modul "+(config.moduleVersion||"")};try{await fetch(ep,{method:"POST",mode:"no-cors",body:new URLSearchParams(payload)});const ok=await verify(ep,sid);if(!ok){sendUI("warn");msg("Sudah dikirim dari browser, tetapi belum terverifikasi. Coba kirim ulang.");return}state.lastSentFingerprint=fp;state.lastSentAt=new Date().toISOString();state.lastSubmissionId=sid;state.pendingSubmissionId="";state.pendingFingerprint="";save();sendUI("ok");msg("Refleksi terverifikasi masuk ke dashboard guru.")}catch(e){sendUI("error");msg("Pengiriman gagal. Refleksi lokal tetap tersimpan.")}}
function snapshot(){return{studentName:document.getElementById("studentName").value.trim(),className:document.getElementById("studentClass").value.trim(),mode,understood:state.reflections?.understood?.trim()||"",confused:state.reflections?.confused?.trim()||"",difficulties:diffs().slice().sort(),confidence:+(state.confidence||0),completedStages:done.size}}
function diffs(){return[...document.querySelectorAll("[data-difficulty]:checked")].map(x=>x.dataset.difficulty)}
function changed(){refreshSend()}
function refreshSend(){const b=document.getElementById("sendFeedback"),s=document.getElementById("sendStatus");if(!b||!s)return;const fp=JSON.stringify(snapshot()),same=!!(state.lastSentFingerprint&&state.lastSentFingerprint===fp);s.className="send-status";if(!(config.feedbackEndpoint||"").trim()){b.disabled=true;s.textContent="Google Sheets belum terhubung."}else if(same){b.disabled=true;s.classList.add("ok");s.textContent="✓ Terkirim "+fmtTime(state.lastSentAt)+" • tidak ada perubahan."}else{b.disabled=false;s.textContent=state.lastSentAt?"Ada perubahan setelah kiriman "+fmtTime(state.lastSentAt)+".":"Belum pernah dikirim."}}
function sendUI(k){const b=document.getElementById("sendFeedback"),s=document.getElementById("sendStatus");s.className="send-status";b.textContent=k==="sending"?"Mengirim...":"Kirim Refleksi";b.disabled=k==="sending";if(k==="sending"){s.classList.add("warn");s.textContent="Mengirim dan memverifikasi..."}else if(k==="ok"){s.classList.add("ok");s.textContent="✓ Terverifikasi "+fmtTime(state.lastSentAt)+".";b.disabled=true}else if(k==="warn"){s.classList.add("warn");s.textContent="Belum terverifikasi. Kirim ulang memakai ID yang sama.";b.disabled=false}else if(k==="error"){s.classList.add("error");s.textContent="Gagal mengirim. Data lokal tetap aman.";b.disabled=false}}
async function verify(ep,sid){for(let i=0;i<3;i++){if(i)await new Promise(r=>setTimeout(r,700));if(await jsonp(ep,sid,5000))return true}return false}
function jsonp(ep,sid,ms){return new Promise(resolve=>{const cb="__ipaAck_"+id().replace(/[^a-zA-Z0-9_$]/g,""),sc=document.createElement("script");let done=false;const fin=v=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];sc.remove();resolve(!!v)};window[cb]=d=>fin(d&&d.ok===true&&d.found===true);sc.src=ep+(ep.includes("?")?"&":"?")+"action=status&submissionId="+encodeURIComponent(sid)+"&callback="+encodeURIComponent(cb)+"&_="+Date.now();sc.onerror=()=>fin(false);document.head.appendChild(sc);const timer=setTimeout(()=>fin(false),ms)})}
function confLabel(v){return v===1?"Perlu bantuan":v===2?"Cukup paham":v===3?"Sudah yakin":""}
function id(){return globalThis.crypto&&typeof crypto.randomUUID==="function"?crypto.randomUUID():Date.now().toString(36)+"-"+Math.random().toString(36).slice(2)+"-"+Math.random().toString(36).slice(2)}
function fmtTime(x){if(!x)return"";return new Date(x).toLocaleString("id-ID",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}
function save(){state.activeStage=active;state.completed=[...done];state.mode=mode;localStorage.setItem(KEY,JSON.stringify(state))}
function msg(m){toast.textContent=m;toast.classList.add("show");clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove("show"),2400)}
})();